/* ---------------------------------------------------------------------------
   Accessory overlays. Painted last, on top of head and markings.

     O outline   G gear body   H highlight / lens / metal   D accent detail

   Positioned against the shared anatomy in heads.ts — glasses sit on the eye
   boxes at rows 12-17, the collar wraps the jaw at rows 25-29.
--------------------------------------------------------------------------- */

import { defineSprite, type PaletteMap, type Sprite } from "../pixel.ts";

const GEAR: PaletteMap = {
  O: "#2b2438",
  G: "#57496b",
  H: "#bfe8f5",
  D: "#ff8a3d",
};

const NONE: Sprite = defineSprite("", GEAR);

/** Round frames. The single most common sona accessory there is. */
const GLASSES: Sprite = defineSprite(
  `
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
.....OOOOOOOO......OOOOOOOO.....
.....OHHHHHHO......OHHHHHHO.....
..OOOOHHHHHHOOOOOOOOHHHHHHOOOO..
.....OHHHHHHO......OHHHHHHO.....
.....OHHHHHHO......OHHHHHHO.....
.....OHHHHHHO......OHHHHHHO.....
.....OHHHHHHO......OHHHHHHO.....
.....OOOOOOOO......OOOOOOOO.....
`,
  GEAR,
);

/** Over-ear cans. Half the fandom's avatars are wearing these. */
const HEADPHONES: Sprite = defineSprite(
  `
................................
................................
................................
................................
................................
..........OOOOOOOOOOOO..........
........OGGGGGGGGGGGGGGO........
......OGGO............OGGO......
....OGGGGO............OGGGGO....
..OGGGGGGO............OGGGGGGO..
..OGDDDDGO............OGDDDDGO..
..OGDDDDGO............OGDDDDGO..
..OGDDDDGO............OGDDDDGO..
..OGDDDDGO............OGDDDDGO..
..OGGGGGGO............OGGGGGGO..
...OGGGGO..............OGGGGO...
....OOOO................OOOO....
`,
  GEAR,
);

/** A snapback with the brim forward. */
const CAP: Sprite = defineSprite(
  `
................................
................................
................................
................................
..........OOOOOOOOOOOO..........
........OGGGGGGGGGGGGGGO........
......OGGGGGGGGGGGGGGGGGGO......
.....OGGGGDDDDDDDDGGGGGGGGO.....
....OGGGGGDDDDDDDDGGGGGGGGGO....
...OGGGGGGGGGGGGGGGGGGGGGGGGO...
..OGGGGGGGGGGGGGGGGGGGGGGGGGGO..
...OOOOOOOOOOOOOOOOOOOOOOOOOO...
`,
  GEAR,
);

/** Collar with a tag, wrapping the jaw. A friend game, not a leash game. */
const COLLAR: Sprite = defineSprite(
  `
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
.....OOOOOOOOOOOOOOOOOOOOOO.....
.....ODDDDDDDDDDDDDDDDDDDDO.....
.....ODDDDDDDDDDDDDDDDDDDDO.....
.....OOOOOOOOOHHHHOOOOOOOOO.....
..............OHHO..............
`,
  GEAR,
);

/** Flower crown. Con photo staple. */
const FLOWERS: Sprite = defineSprite(
  `
................................
................................
................................
................................
................................
................................
................................
................................
........ODO....ODO....ODO.......
.......ODDDO..ODDDO..ODDDO......
.......ODHDO..ODHDO..ODHDO......
........ODO....ODO....ODO.......
`,
  GEAR,
);

/** A con badge on a lanyard. */
const BADGE: Sprite = defineSprite(
  `
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
......OO................OO......
.......OO..............OO.......
........OO............OO........
.........OOOOOOOOOOOOOO.........
.........OHHHHHHHHHHHHO.........
.........ODDDDDDDDDDDDO.........
`,
  GEAR,
);

export interface AccessoryDef {
  readonly id: string;
  readonly name: string;
  readonly sprite: Sprite;
  /** Which palette key takes the player-chosen accent color. */
  readonly tintKey: "D" | "G" | "none";
}

export const ACCESSORIES: readonly AccessoryDef[] = [
  { id: "none", name: "None", sprite: NONE, tintKey: "none" },
  { id: "glasses", name: "Glasses", sprite: GLASSES, tintKey: "none" },
  { id: "headphones", name: "Headphones", sprite: HEADPHONES, tintKey: "D" },
  { id: "cap", name: "Cap", sprite: CAP, tintKey: "D" },
  { id: "collar", name: "Collar", sprite: COLLAR, tintKey: "D" },
  { id: "flowers", name: "Flower crown", sprite: FLOWERS, tintKey: "D" },
  { id: "badge", name: "Con badge", sprite: BADGE, tintKey: "D" },
] as const;

export function accessoryById(id: string): AccessoryDef {
  return ACCESSORIES.find((a) => a.id === id) ?? ACCESSORIES[0]!;
}
